language: go
sudo: required

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x

services:
  - mysql

before_install:
  - go get -u github.com/haya14busa/goverage
  - mysql -e 'CREATE DATABASE sqlfly;'

script:
  - ./cover.sh

notifications:
  email:
    on_success: never
    on_failure: never

after_success:
  - bash <(curl -s https://codecov.io/bash)
